# Copyright (C) 2021 Michael Debertol
#
# This file is part of digitales_register.
#
# digitales_register is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# digitales_register is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with digitales_register.  If not, see <http://www.gnu.org/licenses/>.
#

#######################################################################################################
#                                                                                                     #
# ALL following data is taken from this amazing project: github.com/miDeb/digitales_register  #
#                                                                                                     #
#######################################################################################################

schools = {
    "BBZ Bruneck": "bbz.digitalesregister.it",
    "Cusanus Gymnasium Bruneck": "cusanus-gymnasium.digitalesregister.it",
    "Fachoberschule für Wirtschaft, Grafik und Kommunikation (TFO/WFO Brixen)": "fo-brixen.digitalesregister.it",
    "Fachschule für Hauswirtschaft und Ernährung Kortsch": "fs-kortsch.digitalesregister.it",
    "Fachschule für Land- und Forstwirtschaft Fürstenburg Burgeis": "fs-fuerstenburg.digitalesregister.it",
    "Fachschule Laimburg": "fslaimburg.digitalesregister.it",
    "Fachschule Neumarkt": "fachschule-neumarkt.digitalesregister.it",
    "FOS Meran": "fos-meran.digitalesregister.it",
    "Franziskanergymnasium Bozen": "franziskanergymnasium.digitalesregister.it",
    "FS Dietenheim": "fs-dietenheim.digitalesregister.it",
    "FS Tisens": "fstisens.digitalesregister.it",
    "Grundschule Afing SSP Tschögglberg": "gs-afing.digitalesregister.it",
    "Grundschule Ahrntal": "gs-ahrntal.digitalesregister.it",
    "Grundschule A. Langer (SSP Bozen Europa)": "gs-langer.digitalesregister.it",
    "Grundschule Blumau": "gs-blumau.digitalesregister.it",
    "Grundschule Burgstall": "gsburgstall.digitalesregister.it",
    "Grundschule Flaas SSP Tschögglberg": "gs-flaas.digitalesregister.it",
    "Grundschule Frangart": "gs-frangart.digitalesregister.it",
    "Grundschule Franz Tappeiner": "gsfranztappeiner.digitalesregister.it",
    "Grundschule Geiselsberg": "gs-geiselsberg.digitalesregister.it",
    "Grundschule Girlan": "gs-girlan.digitalesregister.it",
    "Grundschule Goldrain": "gs-goldrain.digitalesregister.it",
    "Grundschule Gries": "gs-gries.digitalesregister.it",
    "Grundschule Innichen": "gs-innichen.digitalesregister.it",
    "Grundschule Jenesien SSP Tschögglberg": "gs-jenesien.digitalesregister.it",
    "Grundschule J. H. Pestalozzi (SSP Bozen Europa)": "gs-bozeneuropa.digitalesregister.it",
    "Grundschule Kaltern": "gs-kaltern.digitalesregister.it",
    "Grundschule Kardaun": "gs-kardaun.digitalesregister.it",
    "Grundschule Karneid": "gs-karneid.digitalesregister.it",
    "Grundschule Kastelbell": "gs-kastelbell.digitalesregister.it",
    "Grundschule Kollmann": "kollmann.digitalesregister.it",
    "Grundschule Latsch": "gs-latsch.digitalesregister.it",
    "Grundschule Leifers": "gs-leifers.digitalesregister.it",
    "Grundschule Luttach / Ahrntal": "gs-luttach.digitalesregister.it",
    "Grundschule Marling": "gs-marling.digitalesregister.it",
    "Grundschule Mittertal": "gs-mittertal.digitalesregister.it",
    "Grundschule Mölten SSP Tschögglberg": "gs-moelten.digitalesregister.it",
    "Grundschule Moos im Passeier": "gs-moos.digitalesregister.it",
    "Grundschule Morter": "gs-morter.digitalesregister.it",
    "Grundschule Niederolang": "gs-niederolang.digitalesregister.it",
    "Grundschule Niederrasen": "gs-niederrasen.digitalesregister.it",
    "Grundschule Niedertal": "gs-niedertal.digitalesregister.it",
    "Grundschule Oberolang": "gs-oberolang.digitalesregister.it",
    "Grundschule Oberrasen": "gs-oberrasen.digitalesregister.it",
    "Grundschule Oswald von Wolkenstein Meran": "gsoswaldvonwolkenstein.digitalesregister.it",
    "Grundschule Partschins": "gs-partschins.digitalesregister.it",
    "Grundschule Platt in Passeier": "gs-platt.digitalesregister.it",
    "Grundschule Prettau / Ahrntal": "gs-prettau.digitalesregister.it",
    "Grundschule Quirein SSP Bozen Stadtzentrum": "gs-quirein.digitalesregister.it",
    "Grundschule Rabenstein in Passeier": "gs-rabenstein.digitalesregister.it",
    "Grundschule R. Stolz SSP Bozen Stadtzentrum": "gs-bozenstadtzentrum.digitalesregister.it",
    "Grundschule Saltaus / St. Martin": "gs-saltaus.digitalesregister.it",
    "Grundschule Sexten": "gs-sexten.digitalesregister.it",
    "Grundschule Steinegg": "gs-steinegg.digitalesregister.it",
    "Grundschule Steinhaus / Ahrntal": "gs-steinhaus.digitalesregister.it",
    "Grundschule Stuls in Passeier": "gs-stuls.digitalesregister.it",
    "Grundschule St. Jakob / Ahrntal": "gs-stjakob.digitalesregister.it",
    "Grundschule St. Johann / Ahrntal": "gs-stjohann.digitalesregister.it",
    "Grundschule St. Leonhard": "gs-stleonhard.digitalesregister.it",
    "Grundschule St. Martin": "gs-stm.digitalesregister.it",
    "Grundschule St. Peter / Ahrntal": "gs-stpeter.digitalesregister.it",
    "Grundschule Tarsch": "gs-tarsch.digitalesregister.it",
    "Grundschule Tiers": "gs-tiers.digitalesregister.it",
    "Grundschule Toblach": "gs-toblach.digitalesregister.it",
    "Grundschule Tschars": "gs-tschars.digitalesregister.it",
    "Grundschule Verschneid SSP Tschögglberg": "gs-verschneid.digitalesregister.it",
    "Grundschule Vierschach": "gs-vierschach.digitalesregister.it",
    "Grundschule Voelseraicha": "gs-voelseraicha.digitalesregister.it",
    "Grundschule Vöran SSP Tschögglberg": "gs-voeran.digitalesregister.it",
    "Grundschule Walten in Passeier": "gs-walten.digitalesregister.it",
    "Grundschule Weissenbach / Ahrntal": "gs-weissenbach.digitalesregister.it",
    "Grundschule Winnebach": "gs-winnebach.digitalesregister.it",
    "Grundschulen im Schulsprengel Laas": "gs-laas.digitalesregister.it",
    "Grundschulen im Schulsprengel Ulten": "gs-ulten.digitalesregister.it",
    "Grundschulen im SSP Deutschnofen": "gs-deutschnofen.digitalesregister.it",
    "Grundschulen im SSP Schlanders": "gs-schlanders.digitalesregister.it",
    "Grundschulen SSP Mals": "sspmals-gs.digitalesregister.it",
    "Grundschulen SSP Naturns": "gs-naturns.digitalesregister.it",
    "Grundschulen SSP Obermais": "gs-ssp-obermais.digitalesregister.it",
    "Grundschulen SSP Schluderns": "gs-schluderns.digitalesregister.it",
    "Grundschulen SSP Terlan": "gs-sspterlan.digitalesregister.it",
    "Grundschulen SSP Untermais": "gs-untermais.digitalesregister.it",
    "Grundschulen Sterzing III (Kematen, Mauls, St. Jakob, Stilfes, Trens, Wiesen)": "gs-sterzing3.digitalesregister.it",
    "Grundschulsprengel Bozen 1 (Goethe, Chini, Wolff)": "bozen1.digitalesregister.it",
    "Grundschulsprengel Brixen": "brixen1.digitalesregister.it",
    "Grundschulsprengel Eppan": "gspeppan.digitalesregister.it",
    "Grundschulsprengel Neumarkt": "gsp-neumarkt.digitalesregister.it",
    "Grunschule Algund": "gs-algund.digitalesregister.it",
    "GS Ahornach": "gs-ahornach.digitalesregister.it",
    "GS Albert Schweitzer": "gsalbertschweitzer.digitalesregister.it",
    "GS Branzoll": "gs-branzoll.digitalesregister.it",
    "GS Feldthurns": "feldthurns.digitalesregister.it",
    "GS Hafling": "hafling.digitalesregister.it",
    "GS Kastelruth": "gs-kastelruth.digitalesregister.it",
    "GS Lappach": "gs-lappach.digitalesregister.it",
    "GS Lengmoos (SSP Ritten)": "lengmoos.digitalesregister.it",
    "GS Lengstein (SSP Ritten)": "lengstein.digitalesregister.it",
    "GS Mühlwald": "gs-muehlwald.digitalesregister.it",
    "GS Niederdorf": "gs-niederdorf.digitalesregister.it",
    "GS Oberinn (SSP Ritten)": "oberinn.digitalesregister.it",
    "GS Pfatten": "gs-pfatten.digitalesregister.it",
    "GS Prags": "gs-prags.digitalesregister.it",
    "GS Rein in Taufers": "gs-reinintaufers.digitalesregister.it",
    "GS Sand in Taufers": "gs-sandintaufers.digitalesregister.it",
    "GS Seis": "gs-seis.digitalesregister.it",
    "GS St. Jakob (SSP Leifers)": "gs-st-jakob.digitalesregister.it",
    "GS St. Michael": "gs-michael.digitalesregister.it",
    "GS St. Oswald": "gs-oswald.digitalesregister.it",
    "GS Verdings": "verdings.digitalesregister.it",
    "GS Vinzenz Goller (GSP Brixen)": "bx-goller.digitalesregister.it",
    "GS Völs": "gs-voels.digitalesregister.it",
    "GS Wahlen": "gs-wahlen.digitalesregister.it",
    "GS Waidbruck": "waidbruck.digitalesregister.it",
    "GSP Klausen 1": "klausen1.digitalesregister.it",
    "GSP Lana": "gsp-lana.digitalesregister.it",
    "GSS Klausen": "gssklausen2.digitalesregister.it",
    "Gymnasien Meran": "gymme.digitalesregister.it",
    "Gymnasium Walther von der Vogelweide Bozen": "vogelweide.digitalesregister.it",
    "Herzjesu Institut": "herzjesu-institut.digitalesregister.it",
    "Kunstgymnasium und Landesberufsschule Cademia": "cademia.digitalesregister.it",
    "Landeshotelfachschule Kaiserhof Meran": "kaiserhof.digitalesregister.it",
    "LBS Schlanders": "lbs-schlanders.digitalesregister.it",
    "LBS Zuegg": "lbszuegg.digitalesregister.it",
    "LHFS Bruneck": "lhfsbruneck.digitalesregister.it",
    "Maria Hueber Gymnasium": "mhg.digitalesregister.it",
    "Mariengarten Zisterzienserinnen-KlosterInternatsschule": "mariengarten.digitalesregister.it",
    "Mittelschule Blumau (SSP Karneid)": "ms-sspkarneid.digitalesregister.it",
    "Mittelschule Bruneck II": "meusburger.digitalesregister.it",
    "Mittelschule Gossensaß": "ms-goss.digitalesregister.it",
    "Mittelschule Jenesien": "ms-jenesien.digitalesregister.it",
    "Mittelschule Kaltern": "ms-kaltern.digitalesregister.it",
    "Mittelschule Klausen": "ms-klausen.digitalesregister.it",
    "Mittelschule Laas": "ms-laas.digitalesregister.it",
    "Mittelschule Leifers": "ms-leifers.digitalesregister.it",
    "Mittelschule Mals": "ms-mals.digitalesregister.it",
    "Mittelschule Mölten": "ms-moelten.digitalesregister.it",
    "Mittelschule Naturns": "ms-naturns.digitalesregister.it",
    "Mittelschule Olang": "ssp-olang.digitalesregister.it",
    "Mittelschule Oswald von Wolkenstein Brixen": "mittelschule-brixen.digitalesregister.it",
    "Mittelschule Peter Rosegger": "ms-untermais.digitalesregister.it",
    "Mittelschule Sand in Taufers": "ms-sand.digitalesregister.it",
    "Mittelschule Schlanders": "ms-schlanders.digitalesregister.it",
    "Mittelschule Schluderns": "ms-schluderns.digitalesregister.it",
    "Mittelschule SSP Bozen Europa (Mittelschule A. Schweitzer)": "ms-bozeneuropa.digitalesregister.it",
    "Mittelschule St. Martin": "ssp-stm.digitalesregister.it",
    "Mittelschule Terlan": "ms-sspterlan.digitalesregister.it",
    "Mittelschule \"Adalbert Stifter\"": "ms-stifter.digitalesregister.it",
    "Mittelschulen SSP Bozen Stadtzentrum": "ms-bozenstadtzentrum.digitalesregister.it",
    "MS Algund": "ms-algund.digitalesregister.it",
    "MS Carl Wolf": "mscarlwolf.digitalesregister.it",
    "MS Latsch": "ms-latsch.digitalesregister.it",
    "MS Neumarkt": "ms-neumarkt.digitalesregister.it",
    "MS Rosegger und Tirol": "ms-untermais.digitalesregister.it",
    "MS Tirol": "ms-tirol.digitalesregister.it",
    "MS Welsberg": "ms-welsberg.digitalesregister.it",
    "Mühlbach": "ssp-muehlbach.digitalesregister.it",
    "Oberbozen (SSP Ritten)": "oberbozen.digitalesregister.it",
    "Oberschulen J. Ph. Fallmerayer": "fallmerayer.digitalesregister.it",
    "Oberschulzentrum Sterzing": "osz-sterzing.digitalesregister.it",
    "OFL Auer": "oflauer.digitalesregister.it",
    "OSZ Sand in Taufers": "sz-sand.digitalesregister.it",
    "OSZ Schlanders": "osz-schlanders.digitalesregister.it",
    "Realgymnasium und Fachoberschule für Bauwesen „Peter Anich“ Bozen": "rg-fob.digitalesregister.it",
    "RG/TFO Albert Einstein Meran": "rgtfo-me.digitalesregister.it",
    "Schulsprengel Eppan": "ssp-eppan.digitalesregister.it",
    "Schulsprengel Ritten": "ssp-ritten.digitalesregister.it",
    "Schulsprengel Schlern": "sspschlern-ms.digitalesregister.it",
    "Schulsprengel Sterzing I (Grundschulen in Sterzing, Gossensaß und Innerpflersch)": "sterzing1.digitalesregister.it",
    "Schulsprengel Tramin": "ssp-tramin.digitalesregister.it",
    "Schulsprengel Vintl": "ssp-vintl.digitalesregister.it",
    "Scola elementera Urtijei / Runcadic": "se-urtijei.digitalesregister.it",
    "Scola Mesana Selva": "sm-selva.digitalesregister.it",
    "Scola mesana Urtijëi": "sm-urtijei.digitalesregister.it",
    "Scores altes La Ila": "scoresaltes.digitalesregister.it",
    "Sozialwissenschaftliches Gymnasium Bozen - Fachoberschule für Tourismus": "sogym-fotour.digitalesregister.it",
    "Sozialwissenschaftliches Gymnasium Bruneck": "sowikunstgym-bruneck.digitalesregister.it",
    "Sozialwissenschaftliches Gymnasium JOSEF GASSER Brixen": "gymnasiumbrixen.digitalesregister.it",
    "SSP Abtei Scora elementara": "gs-abtei.digitalesregister.it",
    "SSP Abtei Scuola media \"Tita Alton\"": "ms-stern.digitalesregister.it",
    "SSP Ahrntal": "ssp-ahrntal.digitalesregister.it",
    "SSP Algund - Grundschulen": "ssp-algund.digitalesregister.it",
    "SSP Bruneck 1": "bruneck1.digitalesregister.it",
    "SSP Deutschnofen": "ssp-deutschnofen.digitalesregister.it",
    "SSP Innichen": "ssp-innichen.digitalesregister.it",
    "SSP Lana Grundschulen": "ssplana-gs.digitalesregister.it",
    "SSP Lana": "ssp-lana.digitalesregister.it",
    "SSP Meran Obermais": "ssp-meran-obermais.digitalesregister.it",
    "SSP Nonsberg Grundschule": "sspnonsberg-gs.digitalesregister.it",
    "SSP Nonsberg Mittelschule": "sspnonsberg-ms.digitalesregister.it",
    "SSP Sarntal": "ssp-sarntal.digitalesregister.it",
    "SSP Sterzing 3 (Vigil Raber)": "schulsprengel-sterzing3.digitalesregister.it",
    "SSP St. Leonhard": "ssp-stleonhard.digitalesregister.it",
    "SSP Toblach": "ssp-toblach.digitalesregister.it",
    "SSP Ulten": "ssp-ulten.digitalesregister.it",
    "TFO Bozen": "tfobz.digitalesregister.it",
    "TFO Bruneck": "tfo-bruneck.digitalesregister.it",
    "Unterinn (SSP Ritten)": "unterinn.digitalesregister.it",
    "Ursulinen": "ursulinen.digitalesregister.it",
    "Villanders - Grundschulsprengel Klausen 2": "villanders.digitalesregister.it",
    "Vinzentinum": "vinzentinum.digitalesregister.it",
    "Waldorf WOB Bozen": "wob.digitalesregister.it",
    "Wangen (SSP Ritten)": "wangen.digitalesregister.it",
    "WFO Auer": "wfoauer.digitalesregister.it",
    "WFO Bozen": "wfobz.digitalesregister.it",
    "WFO Bruneck": "wfo-bruneck.digitalesregister.it",
    "WFO Meran": "wfokafka.digitalesregister.it",
    "WFO Raetia St. Ulrich": "ite-raetia.digitalesregister.it",
}
